// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: demo

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t * ui_mainScreen;
void ui_event_qrutton(lv_event_t * e);
lv_obj_t * ui_qrutton;
lv_obj_t * ui_qrButtonLabel;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Image5;
// CUSTOM VARIABLES


// SCREEN: ui_qrScreen
void ui_qrScreen_screen_init(void);
lv_obj_t * ui_qrScreen;
void ui_event_backButton(lv_event_t * e);
lv_obj_t * ui_backButton;
lv_obj_t * ui_backButtonLabel1;
lv_obj_t * ui_Label5;
void ui_event_creaQRBTN(lv_event_t * e);
lv_obj_t * ui_creaQRBTN;
lv_obj_t * ui_backButtonLabel3;
// CUSTOM VARIABLES


// SCREEN: ui_homeScreen
void ui_homeScreen_screen_init(void);
lv_obj_t * ui_homeScreen;
lv_obj_t * ui_homTabV;
lv_obj_t * ui_profileTabV;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_tenImage;
lv_obj_t * ui_dataName;
lv_obj_t * ui_mailImage;
lv_obj_t * ui_dataEmail;
lv_obj_t * ui_idImage;
lv_obj_t * ui_dataID;
void ui_event_outBtn(lv_event_t * e);
lv_obj_t * ui_outBtn;
lv_obj_t * ui_outName;
lv_obj_t * ui_Image10;
lv_obj_t * ui_shopTabV;
lv_obj_t * ui_Viewall;
lv_obj_t * ui_wetHome;
lv_obj_t * ui_wetImage;
lv_obj_t * ui_wetName;
lv_obj_t * ui_wetGia;
lv_obj_t * ui_chocoHome;
lv_obj_t * ui_chocoImage;
lv_obj_t * ui_chocoName;
lv_obj_t * ui_chocoGia;
lv_obj_t * ui_cocaHome;
lv_obj_t * ui_cocaImage;
lv_obj_t * ui_cocaName;
lv_obj_t * ui_cocaGia;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Cart;
lv_obj_t * ui_cartName;
lv_obj_t * ui_totalName;
void ui_event_paymentBtn(lv_event_t * e);
lv_obj_t * ui_paymentBtn;
lv_obj_t * ui_payName;
lv_obj_t * ui_paygach;
lv_obj_t * ui_gia;
lv_obj_t * ui_paygach1;
lv_obj_t * ui_totalName1;
lv_obj_t * ui_totalName2;
lv_obj_t * ui_sluong;
lv_obj_t * ui_price;
lv_obj_t * ui_totalName5;
lv_obj_t * ui_nhan;
lv_obj_t * ui_nhan1;
lv_obj_t * ui_nhan2;
lv_obj_t * ui_totalName3;
lv_obj_t * ui_totalName4;
lv_obj_t * ui_totalName6;
lv_obj_t * ui_sldata;
lv_obj_t * ui_sldata1;
lv_obj_t * ui_sldata2;
lv_obj_t *ui_errorMessage;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_qrutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_qrScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_qrScreen_screen_init);
        _ui_screen_delete(&ui_mainScreen);
    }
}

void ui_event_backButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainScreen_screen_init);
        _ui_screen_delete(&ui_qrScreen);
    }
}

void ui_event_creaQRBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        crea_qrcode(e);
    }
}



///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_mainScreen_screen_init();
    ui_qrScreen_screen_init();
    ui_homeScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_mainScreen);
}
