// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: demo

#include "ui.h"

void ui_homeScreen_screen_init(void)
{
    ui_homeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_homeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_homTabV = lv_tabview_create(ui_homeScreen, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_homTabV, 799);
    lv_obj_set_height(ui_homTabV, 479);
    lv_obj_set_x(ui_homTabV, 2);
    lv_obj_set_y(ui_homTabV, 0);
    lv_obj_set_align(ui_homTabV, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_homTabV, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_dir(ui_homTabV, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_profileTabV = lv_tabview_add_tab(ui_homTabV, "Profile");
    lv_obj_set_style_bg_color(ui_profileTabV, lv_color_hex(0x09E9F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_profileTabV, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_profileTabV, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_profileTabV, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_profileTabV, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_profileTabV, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_profileTabV);
    lv_obj_set_width(ui_Panel2, 700);
    lv_obj_set_height(ui_Panel2, 350);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -2);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tenImage = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_tenImage, &ui_img_personal_png);
    lv_obj_set_width(ui_tenImage, LV_SIZE_CONTENT);   /// 72
    lv_obj_set_height(ui_tenImage, LV_SIZE_CONTENT);    /// 72
    lv_obj_set_x(ui_tenImage, -281);
    lv_obj_set_y(ui_tenImage, -104);
    lv_obj_set_align(ui_tenImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tenImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tenImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dataName = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_dataName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dataName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dataName, -155);
    lv_obj_set_y(ui_dataName, -100);
    lv_obj_set_align(ui_dataName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dataName, "Loading ...");
    lv_obj_set_style_text_font(ui_dataName, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mailImage = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_mailImage, &ui_img_mail_png);
    lv_obj_set_width(ui_mailImage, LV_SIZE_CONTENT);   /// 72
    lv_obj_set_height(ui_mailImage, LV_SIZE_CONTENT);    /// 71
    lv_obj_set_x(ui_mailImage, -279);
    lv_obj_set_y(ui_mailImage, -31);
    lv_obj_set_align(ui_mailImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mailImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mailImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dataEmail = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_dataEmail, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dataEmail, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dataEmail, -155);
    lv_obj_set_y(ui_dataEmail, -35);
    lv_obj_set_align(ui_dataEmail, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dataEmail, "Loading ...");
    lv_obj_set_style_text_font(ui_dataEmail, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_idImage = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_idImage, &ui_img_id_png);
    lv_obj_set_width(ui_idImage, LV_SIZE_CONTENT);   /// 72
    lv_obj_set_height(ui_idImage, LV_SIZE_CONTENT);    /// 62
    lv_obj_set_x(ui_idImage, -277);
    lv_obj_set_y(ui_idImage, 33);
    lv_obj_set_align(ui_idImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_idImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_idImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dataID = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_dataID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dataID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dataID, -153);
    lv_obj_set_y(ui_dataID, 27);
    lv_obj_set_align(ui_dataID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dataID, "937B2528");
    lv_obj_set_style_text_font(ui_dataID, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outBtn = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_outBtn, 100);
    lv_obj_set_height(ui_outBtn, 50);
    lv_obj_set_x(ui_outBtn, -74);
    lv_obj_set_y(ui_outBtn, 120);
    lv_obj_set_align(ui_outBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_outBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_outBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_outName = lv_label_create(ui_outBtn);
    lv_obj_set_width(ui_outName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_outName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_outName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_outName, "LOG OUT");

    ui_Image10 = lv_img_create(ui_profileTabV);
    lv_img_set_src(ui_Image10, &ui_img_1799328165);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 270
    lv_obj_set_x(ui_Image10, 201);
    lv_obj_set_y(ui_Image10, -6);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_shopTabV = lv_tabview_add_tab(ui_homTabV, "Shop");
    lv_obj_set_style_bg_color(ui_shopTabV, lv_color_hex(0x2CEFFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shopTabV, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_shopTabV, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_shopTabV, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_shopTabV, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_shopTabV, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Viewall = lv_obj_create(ui_shopTabV);
    lv_obj_set_width(ui_Viewall, 280);
    lv_obj_set_height(ui_Viewall, 411);
    lv_obj_set_x(ui_Viewall, -252);
    lv_obj_set_y(ui_Viewall, -2);
    lv_obj_set_align(ui_Viewall, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Viewall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wetHome = lv_obj_create(ui_Viewall);
    lv_obj_set_height(ui_wetHome, 91);
    lv_obj_set_width(ui_wetHome, lv_pct(89));
    lv_obj_set_x(ui_wetHome, -16);
    lv_obj_set_y(ui_wetHome, -122);
    lv_obj_set_align(ui_wetHome, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wetHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wetImage = lv_img_create(ui_wetHome);
    lv_img_set_src(ui_wetImage, &ui_img_khangiay_png);
    lv_obj_set_width(ui_wetImage, LV_SIZE_CONTENT);   /// 144
    lv_obj_set_height(ui_wetImage, LV_SIZE_CONTENT);    /// 215
    lv_obj_set_x(ui_wetImage, -56);
    lv_obj_set_y(ui_wetImage, 2);
    lv_obj_set_align(ui_wetImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wetImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wetImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wetName = lv_label_create(ui_wetHome);
    lv_obj_set_width(ui_wetName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wetName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wetName, 49);
    lv_obj_set_y(ui_wetName, -11);
    lv_obj_set_align(ui_wetName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wetName, "W.WIPES");
    lv_obj_set_style_text_color(ui_wetName, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wetName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wetName, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wetGia = lv_label_create(ui_wetHome);
    lv_obj_set_width(ui_wetGia, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wetGia, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wetGia, 52);
    lv_obj_set_y(ui_wetGia, 17);
    lv_obj_set_align(ui_wetGia, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wetGia, "$1.19");
    lv_obj_set_style_text_color(ui_wetGia, lv_color_hex(0x03B706), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wetGia, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_wetGia, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wetGia, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chocoHome = lv_obj_create(ui_Viewall);
    lv_obj_set_width(ui_chocoHome, 221);
    lv_obj_set_height(ui_chocoHome, 118);
    lv_obj_set_x(ui_chocoHome, -16);
    lv_obj_set_y(ui_chocoHome, 142);
    lv_obj_set_align(ui_chocoHome, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_chocoHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chocoImage = lv_img_create(ui_chocoHome);
    lv_img_set_src(ui_chocoImage, &ui_img_socula_png);
    lv_obj_set_width(ui_chocoImage, LV_SIZE_CONTENT);   /// 144
    lv_obj_set_height(ui_chocoImage, LV_SIZE_CONTENT);    /// 215
    lv_obj_set_x(ui_chocoImage, -50);
    lv_obj_set_y(ui_chocoImage, -1);
    lv_obj_set_align(ui_chocoImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chocoImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_chocoImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chocoName = lv_label_create(ui_chocoHome);
    lv_obj_set_width(ui_chocoName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chocoName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chocoName, 36);
    lv_obj_set_y(ui_chocoName, -18);
    lv_obj_set_align(ui_chocoName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_chocoName, "T.CHOCOLATE");
    lv_obj_set_style_text_color(ui_chocoName, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chocoName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chocoName, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chocoGia = lv_label_create(ui_chocoHome);
    lv_obj_set_width(ui_chocoGia, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chocoGia, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chocoGia, 35);
    lv_obj_set_y(ui_chocoGia, 22);
    lv_obj_set_align(ui_chocoGia, LV_ALIGN_CENTER);
    lv_label_set_text(ui_chocoGia, "$0.79");
    lv_obj_set_style_text_color(ui_chocoGia, lv_color_hex(0x03B706), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chocoGia, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_chocoGia, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chocoGia, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cocaHome = lv_obj_create(ui_Viewall);
    lv_obj_set_width(ui_cocaHome, 223);
    lv_obj_set_height(ui_cocaHome, 145);
    lv_obj_set_x(ui_cocaHome, -16);
    lv_obj_set_y(ui_cocaHome, 4);
    lv_obj_set_align(ui_cocaHome, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cocaHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cocaImage = lv_img_create(ui_cocaHome);
    lv_img_set_src(ui_cocaImage, &ui_img_cocacola_png);
    lv_obj_set_width(ui_cocaImage, LV_SIZE_CONTENT);   /// 144
    lv_obj_set_height(ui_cocaImage, LV_SIZE_CONTENT);    /// 215
    lv_obj_set_x(ui_cocaImage, -64);
    lv_obj_set_y(ui_cocaImage, 7);
    lv_obj_set_align(ui_cocaImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cocaImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cocaImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cocaName = lv_label_create(ui_cocaHome);
    lv_obj_set_width(ui_cocaName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cocaName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cocaName, 40);
    lv_obj_set_y(ui_cocaName, 29);
    lv_obj_set_align(ui_cocaName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cocaName, "$0.47");
    lv_obj_set_style_text_color(ui_cocaName, lv_color_hex(0x03B706), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cocaName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_cocaName, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cocaName, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cocaGia = lv_label_create(ui_cocaHome);
    lv_obj_set_width(ui_cocaGia, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cocaGia, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cocaGia, 35);
    lv_obj_set_y(ui_cocaGia, -23);
    lv_obj_set_align(ui_cocaGia, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cocaGia, "COCA-COLA");
    lv_obj_set_style_text_font(ui_cocaGia, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Viewall);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -14);
    lv_obj_set_y(ui_Label4, -184);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "View all");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x0076D8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cart = lv_obj_create(ui_shopTabV);
    lv_obj_set_width(ui_Cart, 479);
    lv_obj_set_height(ui_Cart, 408);
    lv_obj_set_x(ui_Cart, 143);
    lv_obj_set_y(ui_Cart, -2);
    lv_obj_set_align(ui_Cart, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Cart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cartName = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_cartName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cartName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cartName, 5);
    lv_obj_set_y(ui_cartName, -184);
    lv_obj_set_align(ui_cartName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cartName, "CART");
    lv_obj_set_style_text_color(ui_cartName, lv_color_hex(0xE60A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cartName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cartName, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_totalName = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_totalName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_totalName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_totalName, -190);
    lv_obj_set_y(ui_totalName, 91);
    lv_obj_set_align(ui_totalName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_totalName, "TOTAL:");

    ui_paymentBtn = lv_btn_create(ui_Cart);
    lv_obj_set_width(ui_paymentBtn, 100);
    lv_obj_set_height(ui_paymentBtn, 50);
    lv_obj_set_x(ui_paymentBtn, 161);
    lv_obj_set_y(ui_paymentBtn, 137);
    lv_obj_set_align(ui_paymentBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_paymentBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_paymentBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_payName = lv_label_create(ui_paymentBtn);
    lv_obj_set_width(ui_payName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_payName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_payName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_payName, "PAYMENT");

    ui_paygach = lv_btn_create(ui_Cart);
    lv_obj_set_width(ui_paygach, 455);
    lv_obj_set_height(ui_paygach, 10);
    lv_obj_set_x(ui_paygach, -3);
    lv_obj_set_y(ui_paygach, 62);
    lv_obj_set_align(ui_paygach, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_paygach, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_paygach, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gia = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_gia, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gia, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gia, -70);
    lv_obj_set_y(ui_gia, 91);
    lv_obj_set_align(ui_gia, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gia, "...");

    ui_paygach1 = lv_btn_create(ui_Cart);
    lv_obj_set_width(ui_paygach1, 7);
    lv_obj_set_height(ui_paygach1, 167);
    lv_obj_set_x(ui_paygach1, 71);
    lv_obj_set_y(ui_paygach1, -61);
    lv_obj_set_align(ui_paygach1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_paygach1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_paygach1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_totalName1 = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_totalName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_totalName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_totalName1, -178);
    lv_obj_set_y(ui_totalName1, -98);
    lv_obj_set_align(ui_totalName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_totalName1, "WET WIPES");
    lv_obj_set_style_text_font(ui_totalName1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_totalName2 = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_totalName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_totalName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_totalName2, -175);
    lv_obj_set_y(ui_totalName2, -39);
    lv_obj_set_align(ui_totalName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_totalName2, "COCA-COLA");
    lv_obj_set_style_text_font(ui_totalName2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sluong = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_sluong, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sluong, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sluong, 26);
    lv_obj_set_y(ui_sluong, -141);
    lv_obj_set_align(ui_sluong, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sluong, "Quantity");
    lv_obj_set_style_text_decor(ui_sluong, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sluong, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_price = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_price, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_price, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_price, -74);
    lv_obj_set_y(ui_price, -139);
    lv_obj_set_align(ui_price, LV_ALIGN_CENTER);
    lv_label_set_text(ui_price, "Price");
    lv_obj_set_style_text_decor(ui_price, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_price, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_price, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_price, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_price, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_price, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_totalName5 = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_totalName5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_totalName5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_totalName5, -166);
    lv_obj_set_y(ui_totalName5, 21);
    lv_obj_set_align(ui_totalName5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_totalName5, "T.CHOCOLATE");
    lv_obj_set_style_text_font(ui_totalName5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nhan = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_nhan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nhan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nhan, -24);
    lv_obj_set_y(ui_nhan, -101);
    lv_obj_set_align(ui_nhan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nhan, "x");

    ui_nhan1 = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_nhan1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nhan1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nhan1, -22);
    lv_obj_set_y(ui_nhan1, 20);
    lv_obj_set_align(ui_nhan1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nhan1, "x");

    ui_nhan2 = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_nhan2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nhan2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nhan2, -23);
    lv_obj_set_y(ui_nhan2, -43);
    lv_obj_set_align(ui_nhan2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nhan2, "x");

    ui_totalName3 = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_totalName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_totalName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_totalName3, -76);
    lv_obj_set_y(ui_totalName3, -101);
    lv_obj_set_align(ui_totalName3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_totalName3, "1.19");
    lv_obj_set_style_text_font(ui_totalName3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_totalName4 = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_totalName4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_totalName4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_totalName4, -71);
    lv_obj_set_y(ui_totalName4, 20);
    lv_obj_set_align(ui_totalName4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_totalName4, "0.79");
    lv_obj_set_style_text_font(ui_totalName4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_totalName6 = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_totalName6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_totalName6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_totalName6, -72);
    lv_obj_set_y(ui_totalName6, -42);
    lv_obj_set_align(ui_totalName6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_totalName6, "0.47");
    lv_obj_set_style_text_font(ui_totalName6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sldata = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_sldata, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sldata, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sldata, 24);
    lv_obj_set_y(ui_sldata, -102);
    lv_obj_set_align(ui_sldata, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sldata, "...");

    ui_sldata1 = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_sldata1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sldata1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sldata1, 23);
    lv_obj_set_y(ui_sldata1, -46);
    lv_obj_set_align(ui_sldata1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sldata1, "...");

    ui_sldata2 = lv_label_create(ui_Cart);
    lv_obj_set_width(ui_sldata2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sldata2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sldata2, 24);
    lv_obj_set_y(ui_sldata2, 16);
    lv_obj_set_align(ui_sldata2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sldata2, "...");

    ui_errorMessage = lv_label_create(ui_Cart);  // Parent object
    lv_label_set_text(ui_errorMessage, ""); // Initialize with empty text
    lv_obj_set_pos(ui_errorMessage, 50, 300);  // Set position on the screen

    lv_obj_add_event_cb(ui_outBtn, ui_event_outBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_paymentBtn, ui_event_paymentBtn, LV_EVENT_ALL, NULL);

}
