// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: demo

#include "ui.h"

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainScreen, lv_color_hex(0x2D43FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_mainScreen, lv_color_hex(0xD2DADC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_mainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_mainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_mainScreen, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_qrutton = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_qrutton, 150);
    lv_obj_set_height(ui_qrutton, 60);
    lv_obj_set_x(ui_qrutton, 2);
    lv_obj_set_y(ui_qrutton, -7);
    lv_obj_set_align(ui_qrutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qrutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_qrutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_qrutton, lv_color_hex(0x4EDAF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_qrutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_qrButtonLabel = lv_label_create(ui_qrutton);
    lv_obj_set_width(ui_qrButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_qrButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_qrButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_qrButtonLabel, "Login By QR");
    lv_obj_set_style_text_color(ui_qrButtonLabel, lv_color_hex(0x020000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_qrButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -4);
    lv_obj_set_y(ui_Label1, -144);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "HELLO");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label1, lv_color_hex(0xC65D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -9);
    lv_obj_set_y(ui_Label2, -81);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "  Please select a login QR");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x0E0E0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label2, lv_color_hex(0xC65D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_mainScreen);
    lv_img_set_src(ui_Image5, &ui_img_1799328165);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 198
    lv_obj_set_x(ui_Image5, -7);
    lv_obj_set_y(ui_Image5, 134);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_qrutton, ui_event_qrutton, LV_EVENT_ALL, NULL);

}
