// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: demo

#include "ui.h"

void ui_qrScreen_screen_init(void)
{
    ui_qrScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_qrScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backButton = lv_btn_create(ui_qrScreen);
    lv_obj_set_width(ui_backButton, 100);
    lv_obj_set_height(ui_backButton, 50);
    lv_obj_set_x(ui_backButton, 0);
    lv_obj_set_y(ui_backButton, 155);
    lv_obj_set_align(ui_backButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backButton, lv_color_hex(0x464444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backButtonLabel1 = lv_label_create(ui_backButton);
    lv_obj_set_width(ui_backButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backButtonLabel1, -1);
    lv_obj_set_y(ui_backButtonLabel1, 1);
    lv_obj_set_align(ui_backButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backButtonLabel1, "BACK");
    lv_obj_set_style_text_color(ui_backButtonLabel1, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backButtonLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_backButtonLabel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_qrScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -118);
    lv_obj_set_y(ui_Label5, -48);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5,
                      "1. Open the QuickCart app on your phone.\n\n2. Tap the search QR code icon.\n\n3. Point your camera at the QR code to log in.");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_creaQRBTN = lv_btn_create(ui_qrScreen);
    lv_obj_set_width(ui_creaQRBTN, 258);
    lv_obj_set_height(ui_creaQRBTN, 50);
    lv_obj_set_x(ui_creaQRBTN, 0);
    lv_obj_set_y(ui_creaQRBTN, 90);
    lv_obj_set_align(ui_creaQRBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_creaQRBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_creaQRBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_creaQRBTN, lv_color_hex(0x26A2F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_creaQRBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backButtonLabel3 = lv_label_create(ui_creaQRBTN);
    lv_obj_set_width(ui_backButtonLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backButtonLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backButtonLabel3, -1);
    lv_obj_set_y(ui_backButtonLabel3, 1);
    lv_obj_set_align(ui_backButtonLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backButtonLabel3, "Generate Login QR");
    lv_obj_set_style_text_color(ui_backButtonLabel3, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backButtonLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_backButtonLabel3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backButton, ui_event_backButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_creaQRBTN, ui_event_creaQRBTN, LV_EVENT_ALL, NULL);

}
